### ISSUE TITLE
Commit hash of version tag has changed

### ISSUE THREAD

**Issue by gertvanhoey** [ArthurSonzogni/nlohmann_json_cmake_fetchcontent#2]
First of all, thank you for this repo.  It is very helpful for minimizing bandwidth consumption during continuous integration.

I use the repo via CMake's FetchContent, but referring to the commit hash rather than to the version tag, to avoid that CMake checks the repo each time.  I observed that the hash corresponding with v3.7.3 has changed.  Is this a one time change, or will that happen again in the future ?

**Comment by ArthurSonzogni** [comment]
I am sorry for breaking you! I wasn't expecting people to be using hash instead of the tags.

This happens following this:
https://github.com/ArthurSonzogni/nlohmann_json_cmake_fetchcontent/pull/1#issuecomment-650740174

Now, the repository is fully autonomous. It updates itself autonomously using github action. I think I won't have to every touch this repository anymore. New versions of nlohman_json are queried every weeks.

I expects not touching this repository anymore, but if I have too, I won't rewrite the history anymore. Thanks for filling this issue!

Maybe I can push a branch referencing all the lost commit people like you were using? I will try this tonight.

**Comment by ArthurSonzogni** [comment]
If you still have the hash you were previously using, this would help me confirming I am talking about the correct branch.

**Comment by gertvanhoey** [comment]
I was using commit hash 9cc0abcc4929522faacbe7fa4c2bd070f401b0aa for v3.7.3.  Thank you

**Comment by ArthurSonzogni** [comment]
The old branch is now referenced from old_branch_1
https://github.com/ArthurSonzogni/nlohmann_json_cmake_fetchcontent/tree/old_branch_1

I verified and I was able to shallow-clone this specific commit.
This issue is fixed.

**Comment by gertvanhoey** [comment]
Thank you for fixing
